sudo: false
language: node_js
node_js: node
install:
- travis_retry bundle install
- travis_retry gem install s3_website
- travis_retry pip install awscli --upgrade --user
- travis_retry yarn
script: npm run build:travis
after_script: "./bin/s3_deploy.sh"
cache:
  bundler: true
  directories:
  - node_modules
notifications:
  slack:
    on_pull_requests: false
    secure: ZRC3DvCAynz+Zp5sLYdaozBPRCCO08i8gaQKzEjBwllJSO+5lRfLzjPYlyMJYtmTLq+ILM0CRhoGfCE3o7F/bdtJiEhNxWTsO17JqSlnvttCee0P7zeNIOJUP7mVFjX52yH3yPrCA8WTz97ocdtb9yue4P4bRs4umeEuRFzW0kM=
